# Generated by Django 4.1.dev20220503133153 on 2022-07-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('message', models.TextField(max_length=100)),
            ],
        ),
    ]
